#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --job-name=test-grpo-qwen
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --output=scripts-snellius/slurm_output_%A.out

module purge
module load 2024 
module load CUDA/12.6.0

cd /home/rritter/test/R1-V/

source .venv/bin/activate



# os.environ["HF_ENTITY"]="raoul"
export WANDB_ENTITY="mae-testing" # Added from test-grpo-qwen.job
export WANDB_PROJECT="grpo-testing-vllm" # Added from test-grpo-qwen.job

export DEBUG_MODE="true"
export LOG_PATH="./debug_log_2b.txt" # Updated log path

MODEL_PATH="Qwen/Qwen2-VL-2B-Instruct" # Updated model path
HF_DATASET="leonardPKU/clevr_cogen_a_train" # Updated dataset
OUTPUT_DIR="./share_models/Qwen2-VL-2B-Instruct_GRPO_CLEVR-70k" # Updated output dir
if [ ! -d "$OUTPUT_DIR" ]; then
 mkdir -p "$OUTPUT_DIR"
fi
RUN_NAME="Qwen2-VL-2B-GRPO-CLEVR-70k" # Updated run name
DS_CONFIG="src/r1-v/local_scripts/zero3.json" # Updated deepspeed config path

CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun \
    --nproc_per_node="3" \
    --nnodes="1" \
    --node_rank="0" \
    --master_addr="127.0.0.1" \
    --master_port="12345" \
    /home/rritter/test/R1-V/src/r1-v/src/open_r1/grpo.py \
    --use_vllm true \
    --output_dir "./share_models/Qwen2-VL-2B-Instruct_GRPO_CLEVR-70k-vllm" \
    --model_name_or_path="Qwen/Qwen2-VL-2B-Instruct" \
    --dataset_name="leonardPKU/clevr_cogen_a_train" \
    --max_prompt_length 4096 \
    --max_completion_length 2048 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --learning_rate 1e-6 \
    --lr_scheduler_type "constant" \
    --logging_steps 1 \
    --bf16 true \
    --gradient_checkpointing true \
    --attn_implementation flash_attention_2 \
    --min_pixels 3136 \
    --max_pixels 501760 \
    --num_train_epochs 2 \
    --run_name Qwen2-VL-2B-GRPO-CLEVR-70k-vllm \
    --save_steps 200 \
    --save_total_limit 3 \
    --save_only_model true \
    --report_to wandb \
    --temperature 1.0 \
    --num_generations 8 \
    --vllm_device "cuda:3" \
    --vllm_gpu_memory_utilization 0.8 \
    --deepspeed="/home/rritter/test/R1-V/src/r1-v/local_scripts/zero3.json" \
    2>&1 | tee "./share_models/Qwen2-VL-2B-Instruct_GRPO_CLEVR-70k-vllm/training_log.txt"
